"use client";

// LiveCommentary — Part 5 of the Corporate Earnings Dashboard upgrade.
//
// Fixed-height (300px desktop / 250px mobile) scrollable card displaying
// the latest auto-generated factual commentary entries, newest at the top.
// Each sentence is ≤ 25 words, generated by scripts/generate_commentary.py
// whenever a new quarterly filing lands.
//
// Rules (from spec):
//  - Factual only — no speculation
//  - Max 25 words per entry
//  - Triggered on new results, prioritising large companies + outliers
//  - Shows up to 5 latest entries; hides block entirely if table is empty

import { useEffect, useState } from "react";
import Link from "next/link";
import { formatLastUpdated, formatDate } from "@/lib/format";
import type { LiveCommentary as LC } from "@/lib/types";

export default function LiveCommentary() {
  const [entries, setEntries] = useState<LC[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/commentary?limit=5")
      .then((r) => r.json())
      .then((j) => {
        if (j.ok) setEntries(j.data.entries ?? []);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  // Hide block entirely when no data — spec: "hide if unavailable"
  if (!loading && entries.length === 0) return null;

  const lastUpdated = entries[0]?.updated_at ?? entries[0]?.created_at ?? null;

  return (
    <section className="card overflow-hidden">
      {/* Header row — section label + last-updated stamp */}
      <div className="flex items-center justify-between px-5 pt-4 pb-3 border-b border-core-line">
        <div className="flex items-center gap-2.5">
          <span className="inline-block w-1.5 h-1.5 rounded-full bg-core-pink animate-pulse" />
          <span className="text-[11px] md:text-[12px] uppercase tracking-[0.18em] text-core-ink font-bold">
            Live commentary
          </span>
        </div>
        {lastUpdated ? (
          <span className="text-[10px] text-core-muted tabular-nums">
            {formatLastUpdated(lastUpdated)}
          </span>
        ) : null}
      </div>

      {/* Scrollable body — fixed height, latest items on top, no auto-scroll */}
      <div
        className="overflow-y-auto no-scrollbar"
        style={{ height: "clamp(250px, 30vw, 300px)" }}
      >
        {loading ? (
          <CommentarySkeleton />
        ) : (
          <ul className="divide-y divide-core-line">
            {entries.map((e) => (
              <CommentaryEntry key={e.id} entry={e} />
            ))}
          </ul>
        )}
      </div>
    </section>
  );
}

function CommentaryEntry({ entry }: { entry: LC }) {
  const timeStr = entry.created_at
    ? new Date(entry.created_at).toLocaleTimeString("en-IN", {
        timeZone: "Asia/Kolkata",
        hour: "numeric",
        minute: "2-digit",
        hour12: true,
      })
    : null;

  return (
    <li className="px-5 py-3.5 hover:bg-core-surface/50 transition-colors">
      {/* Company + quarter meta */}
      <div className="flex items-baseline justify-between gap-2 mb-1">
        <div className="flex items-baseline gap-2 min-w-0">
          {entry.ticker ? (
            <Link
              href={`/company/${encodeURIComponent(entry.ticker)}`}
              className="text-[12px] font-bold text-core-ink hover:text-core-pink truncate leading-tight"
            >
              {entry.company}
            </Link>
          ) : (
            <span className="text-[12px] font-bold text-core-ink truncate leading-tight">
              {entry.company}
            </span>
          )}
          {entry.quarter ? (
            <span className="text-[10px] text-core-muted shrink-0">· {entry.quarter}</span>
          ) : null}
        </div>
        {timeStr ? (
          <span className="text-[10px] text-core-muted tabular-nums shrink-0">{timeStr}</span>
        ) : null}
      </div>
      {/* Commentary text — the 25-word factual sentence */}
      <p className="text-[13px] text-core-ink leading-snug">{entry.text}</p>
    </li>
  );
}

function CommentarySkeleton() {
  return (
    <ul className="divide-y divide-core-line">
      {[...Array(4)].map((_, i) => (
        <li key={i} className="px-5 py-3.5 animate-pulse">
          <div className="flex items-center gap-3 mb-2">
            <div className="h-3 w-28 bg-core-line rounded" />
            <div className="h-3 w-12 bg-core-line rounded ml-auto" />
          </div>
          <div className="h-3 w-full bg-core-line rounded mb-1.5" />
          <div className="h-3 w-3/4 bg-core-line rounded" />
        </li>
      ))}
    </ul>
  );
}
