// Starter universe: top-100 NSE-listed Indian companies by market cap.
// Used by the ingestion script when INGEST_TICKERS env var is not set.
// This list mirrors the SQL seed; add rows here + a matching `companies` row
// when expanding. Sector/industry here is informational — the DB is the
// source of truth used by the frontend.

export interface TickerSeed {
  ticker: string;
  name: string;
  exchange: "NSE" | "BSE";
  sector: string;
}

export const TICKERS: TickerSeed[] = [
  { ticker: "RELIANCE.NS",   name: "Reliance Industries",       exchange: "NSE", sector: "Energy" },
  { ticker: "TCS.NS",        name: "Tata Consultancy Services", exchange: "NSE", sector: "Information Technology" },
  { ticker: "HDFCBANK.NS",   name: "HDFC Bank",                 exchange: "NSE", sector: "Financials" },
  { ticker: "INFY.NS",       name: "Infosys",                   exchange: "NSE", sector: "Information Technology" },
  { ticker: "ICICIBANK.NS",  name: "ICICI Bank",                exchange: "NSE", sector: "Financials" },
  { ticker: "SBIN.NS",       name: "State Bank of India",       exchange: "NSE", sector: "Financials" },
  { ticker: "LT.NS",         name: "Larsen & Toubro",           exchange: "NSE", sector: "Industrials" },
  { ticker: "ITC.NS",        name: "ITC",                       exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "HINDUNILVR.NS", name: "Hindustan Unilever",        exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "BHARTIARTL.NS", name: "Bharti Airtel",             exchange: "NSE", sector: "Communication Services" },
  { ticker: "KOTAKBANK.NS",  name: "Kotak Mahindra Bank",       exchange: "NSE", sector: "Financials" },
  { ticker: "AXISBANK.NS",   name: "Axis Bank",                 exchange: "NSE", sector: "Financials" },
  { ticker: "ASIANPAINT.NS", name: "Asian Paints",              exchange: "NSE", sector: "Materials" },
  { ticker: "MARUTI.NS",     name: "Maruti Suzuki",             exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "BAJFINANCE.NS", name: "Bajaj Finance",             exchange: "NSE", sector: "Financials" },
  { ticker: "HCLTECH.NS",    name: "HCL Technologies",          exchange: "NSE", sector: "Information Technology" },
  { ticker: "WIPRO.NS",      name: "Wipro",                     exchange: "NSE", sector: "Information Technology" },
  { ticker: "SUNPHARMA.NS",  name: "Sun Pharmaceutical",        exchange: "NSE", sector: "Healthcare" },
  { ticker: "TITAN.NS",      name: "Titan Company",             exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "ULTRACEMCO.NS", name: "UltraTech Cement",          exchange: "NSE", sector: "Materials" },
  { ticker: "NESTLEIND.NS",  name: "Nestle India",              exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "POWERGRID.NS",  name: "Power Grid Corporation",    exchange: "NSE", sector: "Utilities" },
  { ticker: "NTPC.NS",       name: "NTPC",                      exchange: "NSE", sector: "Utilities" },
  { ticker: "ONGC.NS",       name: "Oil & Natural Gas Corp",    exchange: "NSE", sector: "Energy" },
  { ticker: "TATAMOTORS.NS", name: "Tata Motors",               exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "TATASTEEL.NS",  name: "Tata Steel",                exchange: "NSE", sector: "Materials" },
  { ticker: "JSWSTEEL.NS",   name: "JSW Steel",                 exchange: "NSE", sector: "Materials" },
  { ticker: "ADANIENT.NS",   name: "Adani Enterprises",         exchange: "NSE", sector: "Industrials" },
  { ticker: "ADANIPORTS.NS", name: "Adani Ports",               exchange: "NSE", sector: "Industrials" },
  { ticker: "COALINDIA.NS",  name: "Coal India",                exchange: "NSE", sector: "Energy" },
  { ticker: "BAJAJ-AUTO.NS", name: "Bajaj Auto",                exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "HEROMOTOCO.NS", name: "Hero MotoCorp",             exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "M&M.NS",        name: "Mahindra & Mahindra",       exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "EICHERMOT.NS",  name: "Eicher Motors",             exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "DRREDDY.NS",    name: "Dr Reddy's Laboratories",   exchange: "NSE", sector: "Healthcare" },
  { ticker: "CIPLA.NS",      name: "Cipla",                     exchange: "NSE", sector: "Healthcare" },
  { ticker: "DIVISLAB.NS",   name: "Divis Laboratories",        exchange: "NSE", sector: "Healthcare" },
  { ticker: "APOLLOHOSP.NS", name: "Apollo Hospitals",          exchange: "NSE", sector: "Healthcare" },
  { ticker: "BRITANNIA.NS",  name: "Britannia Industries",      exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "TATACONSUM.NS", name: "Tata Consumer Products",    exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "GRASIM.NS",     name: "Grasim Industries",         exchange: "NSE", sector: "Materials" },
  { ticker: "INDUSINDBK.NS", name: "IndusInd Bank",             exchange: "NSE", sector: "Financials" },
  { ticker: "BAJAJFINSV.NS", name: "Bajaj Finserv",             exchange: "NSE", sector: "Financials" },
  { ticker: "SBILIFE.NS",    name: "SBI Life Insurance",        exchange: "NSE", sector: "Financials" },
  { ticker: "HDFCLIFE.NS",   name: "HDFC Life Insurance",       exchange: "NSE", sector: "Financials" },
  { ticker: "TECHM.NS",      name: "Tech Mahindra",             exchange: "NSE", sector: "Information Technology" },
  { ticker: "LTIM.NS",       name: "LTIMindtree",               exchange: "NSE", sector: "Information Technology" },
  { ticker: "HINDALCO.NS",   name: "Hindalco Industries",       exchange: "NSE", sector: "Materials" },
  { ticker: "SHRIRAMFIN.NS", name: "Shriram Finance",           exchange: "NSE", sector: "Financials" },
  { ticker: "DABUR.NS",      name: "Dabur India",               exchange: "NSE", sector: "Consumer Staples" },
  // Next-50 expansion candidates (frontend will simply show "no data" until
  // the row exists in the DB; seed them when ready to track).
  { ticker: "GODREJCP.NS",   name: "Godrej Consumer Products",  exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "PIDILITIND.NS", name: "Pidilite Industries",       exchange: "NSE", sector: "Materials" },
  { ticker: "SIEMENS.NS",    name: "Siemens",                   exchange: "NSE", sector: "Industrials" },
  { ticker: "AMBUJACEM.NS",  name: "Ambuja Cements",            exchange: "NSE", sector: "Materials" },
  { ticker: "DLF.NS",        name: "DLF",                       exchange: "NSE", sector: "Real Estate" },
  { ticker: "VEDL.NS",       name: "Vedanta",                   exchange: "NSE", sector: "Materials" },
  { ticker: "SAIL.NS",       name: "Steel Authority of India",  exchange: "NSE", sector: "Materials" },
  { ticker: "TRENT.NS",      name: "Trent",                     exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "ZOMATO.NS",     name: "Zomato",                    exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "DMART.NS",      name: "Avenue Supermarts",         exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "GAIL.NS",       name: "GAIL (India)",              exchange: "NSE", sector: "Energy" },
  { ticker: "IOC.NS",        name: "Indian Oil Corporation",    exchange: "NSE", sector: "Energy" },
  { ticker: "BPCL.NS",       name: "Bharat Petroleum",          exchange: "NSE", sector: "Energy" },
  { ticker: "HINDPETRO.NS",  name: "Hindustan Petroleum",       exchange: "NSE", sector: "Energy" },
  { ticker: "ICICIPRULI.NS", name: "ICICI Prudential Life",     exchange: "NSE", sector: "Financials" },
  { ticker: "ICICIGI.NS",    name: "ICICI Lombard General Ins", exchange: "NSE", sector: "Financials" },
  { ticker: "MUTHOOTFIN.NS", name: "Muthoot Finance",           exchange: "NSE", sector: "Financials" },
  { ticker: "CHOLAFIN.NS",   name: "Cholamandalam Investment",  exchange: "NSE", sector: "Financials" },
  { ticker: "PNB.NS",        name: "Punjab National Bank",      exchange: "NSE", sector: "Financials" },
  { ticker: "BANKBARODA.NS", name: "Bank of Baroda",            exchange: "NSE", sector: "Financials" },
  { ticker: "CANBK.NS",      name: "Canara Bank",               exchange: "NSE", sector: "Financials" },
  { ticker: "UNIONBANK.NS",  name: "Union Bank of India",       exchange: "NSE", sector: "Financials" },
  { ticker: "IDFCFIRSTB.NS", name: "IDFC First Bank",           exchange: "NSE", sector: "Financials" },
  { ticker: "LICI.NS",       name: "Life Insurance Corp",       exchange: "NSE", sector: "Financials" },
  { ticker: "HAVELLS.NS",    name: "Havells India",             exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "BOSCHLTD.NS",   name: "Bosch",                     exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "TVSMOTOR.NS",   name: "TVS Motor",                 exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "ASHOKLEY.NS",   name: "Ashok Leyland",             exchange: "NSE", sector: "Industrials" },
  { ticker: "BEL.NS",        name: "Bharat Electronics",        exchange: "NSE", sector: "Industrials" },
  { ticker: "HAL.NS",        name: "Hindustan Aeronautics",     exchange: "NSE", sector: "Industrials" },
  { ticker: "IRCTC.NS",      name: "IRCTC",                     exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "NAUKRI.NS",     name: "Info Edge",                 exchange: "NSE", sector: "Communication Services" },
  { ticker: "PAYTM.NS",      name: "One 97 Communications",     exchange: "NSE", sector: "Financials" },
  { ticker: "NYKAA.NS",      name: "FSN E-Commerce Ventures",   exchange: "NSE", sector: "Consumer Discretionary" },
  { ticker: "POLYCAB.NS",    name: "Polycab India",             exchange: "NSE", sector: "Industrials" },
  { ticker: "MARICO.NS",     name: "Marico",                    exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "COLPAL.NS",     name: "Colgate-Palmolive (India)", exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "MCDOWELL-N.NS", name: "United Spirits",            exchange: "NSE", sector: "Consumer Staples" },
  { ticker: "BERGEPAINT.NS", name: "Berger Paints",             exchange: "NSE", sector: "Materials" },
  { ticker: "ACC.NS",        name: "ACC",                       exchange: "NSE", sector: "Materials" },
  { ticker: "SHREECEM.NS",   name: "Shree Cement",              exchange: "NSE", sector: "Materials" },
  { ticker: "DALBHARAT.NS",  name: "Dalmia Bharat",             exchange: "NSE", sector: "Materials" },
  { ticker: "JINDALSTEL.NS", name: "Jindal Steel & Power",      exchange: "NSE", sector: "Materials" },
  { ticker: "LUPIN.NS",      name: "Lupin",                     exchange: "NSE", sector: "Healthcare" },
  { ticker: "BIOCON.NS",     name: "Biocon",                    exchange: "NSE", sector: "Healthcare" },
  { ticker: "ZYDUSLIFE.NS",  name: "Zydus Lifesciences",        exchange: "NSE", sector: "Healthcare" },
  { ticker: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals",   exchange: "NSE", sector: "Healthcare" },
  { ticker: "MAXHEALTH.NS",  name: "Max Healthcare",            exchange: "NSE", sector: "Healthcare" },
  { ticker: "FORTIS.NS",     name: "Fortis Healthcare",         exchange: "NSE", sector: "Healthcare" },
  { ticker: "PFC.NS",        name: "Power Finance Corporation", exchange: "NSE", sector: "Financials" },
  { ticker: "RECLTD.NS",     name: "REC",                       exchange: "NSE", sector: "Financials" },
  { ticker: "IRFC.NS",       name: "Indian Railway Finance Corp", exchange: "NSE", sector: "Financials" }
];
