// Shared types used across API routes and components.
// Updated: April 2026 — Corporate Earnings Dashboard upgrade.

export interface Company {
  id: string;
  company_name: string;
  ticker: string;
  exchange: string;
  sector: string | null;
  industry: string | null;
  isin: string | null;
  market_cap_bucket: string | null;
  next_result_date: string | null;
  is_active: boolean;
}

export type DataQuality = "ok" | "partial" | "missing" | "stale";

export interface QuarterlyFinancial {
  id: string;
  company_id: string;
  ticker: string;
  quarter_label: string;
  quarter_end_date: string;
  fiscal_year: number;
  fiscal_quarter: number;
  revenue: number | null;
  net_profit: number | null;
  operating_profit: number | null;
  eps: number | null;
  currency: string;
  source: string;
  data_quality_status: DataQuality;
  fetched_at: string;
}

export interface LatestQuarterRow {
  company_id: string;
  company_name: string;
  sector: string | null;
  industry: string | null;
  exchange: string;
  ticker: string;
  quarter_label: string;
  quarter_end_date: string;
  revenue: number | null;
  net_profit: number | null;
  operating_profit: number | null;
  eps: number | null;
  data_quality_status: DataQuality;
  fetched_at: string;
  // Growth fields are computed at the API layer, not stored:
  revenue_yoy?: number | null;
  revenue_qoq?: number | null;
  profit_yoy?: number | null;
  profit_qoq?: number | null;
  // Official filing PDF URL, from the matching announcement_events.raw_json.
  // Null when no filing has been captured for this quarter.
  filing_url?: string | null;
  // Last 8 quarters of revenue, for sparklines:
  revenue_trend?: Array<{ q: string; v: number | null }>;
  // When the company is scheduled to announce the currently-selected quarter.
  // Only populated on rows that haven't reported yet.
  next_result_date?: string | null;
  // The actual date the company filed these numbers (distinct from the
  // quarter-end date). Primary trust signal on the UI.
  result_date?: string | null;
  // User-facing status. Maps to exactly four strings in the UI.
  status?: "announced_with_numbers" | "announced" | "scheduled" | "awaiting";
  // Data source. Used to show "Verified from filing" confidence badge.
  // Values: 'nse' | 'bse' | 'screener' | 'yahoo' | 'unknown'
  source?: string | null;
  // Whether revenue figure may be mis-mapped for this industry type
  // (banks/NBFCs use Total Income / NII, not traditional revenue).
  revenue_note?: "bank_nii" | "insurance_premium" | null;
  // Fields flagged by validation (e.g. revenue too low for company size,
  // YoY > 1000%, profit unrealistic). Shown as a subtle warning chip.
  data_flags?: string[];
}

// -----------------------------------------------------------------------
// Live commentary — auto-generated factual one-sentence summaries.
// Generated by scripts/generate_commentary.py; stored in live_commentary.
// -----------------------------------------------------------------------
export interface LiveCommentary {
  id: string;
  company: string;
  ticker: string | null;
  quarter: string | null;
  text: string;
  source: "auto" | "manual";
  created_at: string;
  updated_at: string;
}

// -----------------------------------------------------------------------
// Expert quotes — curated management / analyst commentary from public
// earnings calls, investor presentations, and press quotes.
// -----------------------------------------------------------------------
export interface ExpertQuote {
  id: string;
  expert_name: string;
  photo_url: string | null;
  designation: string | null;
  firm: string | null;
  quote: string;
  source_url: string | null;
  source_name: string | null;
  published_date: string | null;
  ticker: string | null;
  quarter: string | null;
  created_at: string;
}
